name: Codex Runtime
on:
  schedule:
    - cron: "0 0 * * 0"
env:
  PRESERVATION_VAULT_REMOTE: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/PreservationVault.git"
jobs:
  run-codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r meta_mega_codex/requirements.txt
      - name: Initialize PreservationVault git repository
        run: |
          set -euo pipefail
          mkdir -p meta_mega_codex/PreservationVault
          if [ ! -d meta_mega_codex/PreservationVault/.git ]; then
            git -C meta_mega_codex/PreservationVault init
            git -C meta_mega_codex/PreservationVault config user.name "github-actions[bot]"
            git -C meta_mega_codex/PreservationVault config user.email "github-actions[bot]@users.noreply.github.com"
            git -C meta_mega_codex/PreservationVault checkout -b main
            git -C meta_mega_codex/PreservationVault remote add origin "${PRESERVATION_VAULT_REMOTE}"
            git -C meta_mega_codex/PreservationVault commit --allow-empty -m "Vault init"
          elif [ -z "$(git -C meta_mega_codex/PreservationVault remote)" ]; then
            git -C meta_mega_codex/PreservationVault remote add origin "${PRESERVATION_VAULT_REMOTE}"
          fi
      - run: ./meta_mega_codex/run_and_log.sh meta_mega_codex/stacks/kim_watson_stack.yaml
      - run: cd meta_mega_codex/PreservationVault && git push
